// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.extensions.blocklist.useMLBF", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.blocklist.useMLBF.stashes", true);
user_pref("app.normandy.user_id", "16349aff-a683-4c1c-a730-5029685c6fa4");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1596731059);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1596731034);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1596783179);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1596731179);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1596731090);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 32561);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1596731029);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{dbe09e3e-61fb-4e96-a5a8-871925a45f29}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "yandex");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://yandex.com\",\"label\":\"@яндекс\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1596783180354");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1596784959354");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1596783180909");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1596786780909");
user_pref("browser.search.region", "RU");
user_pref("browser.slowStartup.averageTime", 13058);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200720193547");
user_pref("browser.startup.homepage_override.mstone", "79.0");
user_pref("browser.startup.lastColdStartupCheck", 1596783178);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"adblockultimate_adblockultimate_net-browser-action\",\"support_lastpass_com-browser-action\",\"jid1-kt2kyygi32zpuw_jetpack-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"adblockultimate_adblockultimate_net-browser-action\",\"support_lastpass_com-browser-action\",\"jid1-kt2kyygi32zpuw_jetpack-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Яндекс");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1596731031585");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "79.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "aa5ee8d5c66c46c3ba66f2fcf8da1230");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200720193547");
user_pref("extensions.lastAppVersion", "79.0");
user_pref("extensions.lastPlatformVersion", "79.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.adblockultimate@adblockultimate.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-Kt2kYYgi32zPuw@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.support@lastpass.com", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"038cae18-93bc-4045-a0c6-f56bfc10ce89\",\"formautofill@mozilla.org\":\"288f0768-84d7-4337-8605-fc012b5be76a\",\"screenshots@mozilla.org\":\"e3126b0e-0f2d-437e-bfdc-a8ad0abaf81e\",\"webcompat-reporter@mozilla.org\":\"0ba3a6f0-a456-4300-ac10-eafc9d10d9d6\",\"webcompat@mozilla.org\":\"9274f2a1-e0fb-4a70-b781-59ada61dbf87\",\"default-theme@mozilla.org\":\"31c6d0e8-93ec-4c76-8618-0bdc9a292ea8\",\"google@search.mozilla.org\":\"d88b48a7-32b8-48a7-bf1a-17f4730b03b9\",\"wikipedia@search.mozilla.org\":\"f9e9e902-73a9-4657-95fd-597d2d72cae4\",\"yandex@search.mozilla.org\":\"478d9509-74ae-4f79-aeb0-6dcd62c568ec\",\"ddg@search.mozilla.org\":\"57af2a75-4cbd-4eb2-ba14-3020ef36e450\",\"priceru@search.mozilla.org\":\"2f0ae067-45fe-4149-9638-331fcecb82e9\",\"mailru@search.mozilla.org\":\"f1ba143e-d18c-4637-90de-dc7465b2b221\",\"ozonru@search.mozilla.org\":\"1a38e60b-e75e-4759-8355-33469dc5a148\",\"adblockultimate@adblockultimate.net\":\"92e45fdd-118b-46c3-8db2-39ba0b67177d\",\"support@lastpass.com\":\"bb3c3b7e-cd37-4c7a-a042-bfa8a45a2d3b\",\"jid1-Kt2kYYgi32zPuw@jetpack\":\"60b1cc09-ad53-4095-92d6-125d975ca670\"}");
user_pref("identity.fxaccounts.toolbar.accessed", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "33504d9a-0134-43da-9f52-5a65c4a6dc96");
user_pref("security.sandbox.plugin.tempDirSuffix", "c47a5cc4-8279-4aed-9820-db5ba5ec0dcd");
user_pref("toolkit.startup.last_success", 1596783177);
user_pref("toolkit.telemetry.cachedClientID", "ecf46fa4-c3d9-495f-82ce-832acf23a76a");
user_pref("toolkit.telemetry.previousBuildID", "20200720193547");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
